#THIS FILE WILL BE FOR ALL SAMPLE DATA GENERATION


INSERT INTO conference(conference_id, floor_plan, conference_name, start_date, end_date, location, logo_url) VALUES(1, "https://lol.com", "Senior Design Competition", "2017-03-19", "2017-03-20", "4580 Maryland Pkwy", "http://i.imgur.com/3TLT7QN.png");

INSERT INTO permissions(permission_name) VALUES("xhb");
INSERT INTO permissions(permission_name) VALUES("adm");
INSERT INTO permissions(permission_name) VALUES("org");

INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("9", "Demand Responsive Pedestrian Safety Rumble Strips", 0, "2017-03-28 00:00:00", "0.0.0.0", "DRPSRS@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("10", "Hoover Dam Security Checkpoint", 0, "2017-03-28 00:00:00", "0.0.0.0", "HDSC@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("11", "LVB Light Rail", 0, "2017-03-28 00:00:00", "0.0.0.0", "LVBLR@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("12", "UNLV Paradise Campus Flooding", 0, "2017-03-28 00:00:00", "0.0.0.0", "UNLVPCF@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("13", "Custom Autonomous Secure Home (CASH)", 0, "2017-03-28 00:00:00", "0.0.0.0", "CASH@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("14", "Convention Logistics Tracker", 0, "2017-03-28 00:00:00", "0.0.0.0", "CLT@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("15", "Filterable Stock News Scanner (FLTR)", 0, "2017-03-28 00:00:00", "0.0.0.0", "FLTR@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("16", "Linked", 0, "2017-03-28 00:00:00", "0.0.0.0", "Linked@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("17", "Spots", 0, "2017-03-28 00:00:00", "0.0.0.0", "spots@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("18", "Adaptive Power Supply", 0, "2017-03-28 00:00:00", "0.0.0.0", "APS@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("19", "Card Shoe Projection System", 0, "2017-03-28 00:00:00", "0.0.0.0", "CSPS@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("20", "Casino Dice Project", 0, "2017-03-28 00:00:00", "0.0.0.0", "CDP@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("21", "Impact Solutions", 0, "2017-03-28 00:00:00", "0.0.0.0", "IS@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("22", "Micro Grid II: Controls and Revisions", 0, "2017-03-28 00:00:00", "0.0.0.0", "MCII@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("23", "The Electrical Tester", 0, "2017-03-28 00:00:00", "0.0.0.0", "TET@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("24", "The Hi Ball", 0, "2017-03-28 00:00:00", "0.0.0.0", "THB@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("25", "Bombyx Mori Silk AntiMicrobial Gel", 0, "2017-03-28 00:00:00", "0.0.0.0", "BMSAG@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("26", "Coanda Quadcopter", 0, "2017-03-28 00:00:00", "0.0.0.0", "CQ@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("27", "Damping System Test Drop Tower", 0, "2017-03-28 00:00:00", "0.0.0.0", "DSTDT@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("28", "Harco Spray Gun", 0, "2017-03-28 00:00:00", "0.0.0.0", "HSG@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("29", "Jox-T", 0, "2017-03-28 00:00:00", "0.0.0.0", "Jox-t@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("30", "Automated Heliodon V2.0", 0, "2017-03-28 00:00:00", "0.0.0.0", "AH2@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("31", "Universally Expanding Cage", 0, "2017-03-28 00:00:00", "0.0.0.0", "UEC@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("32", "Wastewater Evaporator", 0, "2017-03-28 00:00:00", "0.0.0.0", "WE@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("33", "Accurate Photo-Emitting Liquid (APEL) Scan", 0, "2017-03-28 00:00:00", "0.0.0.0", "APEL@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("34", "Carpal Tunnel Relief Massager", 0, "2017-03-28 00:00:00", "0.0.0.0", "CTRM@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("35", "Hailey's Hang V3.0", 0, "2017-03-28 00:00:00", "0.0.0.0", "HHV3@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("36", "Silicon Photomultiplier High Energy Radiation Detector", 0, "2017-03-28 00:00:00", "0.0.0.0", "SPHERD@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("37", "Z-Med Alert", 0, "2017-03-28 00:00:00", "0.0.0.0", "ZMED@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("38", "Project Apollo", 0, "2017-03-28 00:00:00", "0.0.0.0", "PA@sdc.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("39", "Micro Grid II: Load Share", 0, "2017-03-28 00:00:00", "0.0.0.0", "MGIILS@sdc.com", 0, 1);

INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("DRPSRS@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("HDSC@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("LVBLR@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("UNLVPCF@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("CASH@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("CLT@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("FLTR@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("Linked@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("spots@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("APS@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("CSPS@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("CDP@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("IS@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("MCII@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("TET@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("THB@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("BMSAG@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("CQ@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("DSTDT@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("HSG@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("Jox-t@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("AH2@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("UEC@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("WE@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("APEL@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("CTRM@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("HHV3@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("SPHERD@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("ZMED@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("PA@sdc.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("MGIILS@sdc.com",1);

INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("DRPSRS@sdc.com",1, "Demand Responsive Pedestrian Safety Rumble Strips", "http://i.imgur.com/3TLT7QN.png", "The Demand Responsive Pedestrian Safety Rumble Strips (DRRS) is an innovative technology that increases pedestrian safety while reducing distracted driving.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("HDSC@sdc.com",1, "Hoover Dam Security Checkpoint", "http://i.imgur.com/3TLT7QN.png", "The Demand Responsive Pedestrian Safety Rumble Strips (DRRS) is an innovative technology that increases pedestrian safety while reducing distracted driving.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("LVBLR@sdc.com",1, "LVB Light Rail", "http://i.imgur.com/3TLT7QN.png", "This project aims to implement a high-speed transportation system in order to satisfy both the need for a connection through McCarran Airport, the Las Vegas Strip, and Downtown Las Vegas and relieve vehicle congestion.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("UNLVPCF@sdc.com",1, "UNLV Paradise Campus Flooding", "http://i.imgur.com/3TLT7QN.png", "The team’s solution is to flatten the parking lot and incorporate porous pavement, along with adding solar panels to generate power and to shade the parking lot.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("CASH@sdc.com",1, "Custom Autonomous Secure Home (CASH)", "http://i.imgur.com/3TLT7QN.png", "Our concept is to develop an application, which allows a user to integrate off-the-shelf home efficiency and security devices as these devices are purchased over time i.e. “plug and play”.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("CLT@sdc.com",1, "Convention Logistics Tracker", "http://i.imgur.com/3TLT7QN.png", "The CLT app is developed with its focus on the attendee experience.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("FLTR@sdc.com",1, "Filterable Stock News Scanner (FLTR)", "http://i.imgur.com/3TLT7QN.png", "We are here to provide a real-time on-demand platform that gives our users the sought-after news filter feature like the solutions currently available.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("Linked@sdc.com",1, "Linked", "http://i.imgur.com/3TLT7QN.png", "We are here to provide a real-time on-demand platform that gives our users the sought-after news filter feature like the solutions currently available.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("spots@sdc.com",1, "Spots", "http://i.imgur.com/3TLT7QN.png", "Spots will facilitate parking in parking lots with regular drivers by integrating all parking spaces on campus in a single system that will track parking spaces to notify and advise students and staff with important information about the parking spots on every lot.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("APS@sdc.com",1, "Adaptive Power Supply", "http://i.imgur.com/3TLT7QN.png", "At a basic level, our solution is a charger that operates to the highest USB 3.0 standard to allow for the charging of multiple devices with varying power ratings and charging requirements.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("CSPS@sdc.com",1, "Card Shoe Projection System", "http://i.imgur.com/3TLT7QN.png", "Our objective is to create a marketable product that can be used to assist casinos and businesses in hindering players from using advantage play, specifically edge-sorting.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("CDP@sdc.com",1, "Casino Dice Project", "http://i.imgur.com/3TLT7QN.png", "Our solution with the advice of Dr. Sahl’s proposal was to have flashing LED dice that randomly settle on a specific color once rolled.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("IS@sdc.com",1, "Impact Solutions", "http://i.imgur.com/3TLT7QN.png", "The purpose of our project is to detect the level of force when a football player is hit.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("MCII@sdc.com",1, "Micro Grid II: Controls and Revisions", "http://i.imgur.com/3TLT7QN.png", "Conversion to a 24V DC system which includes a battery backup system for the controls allows maximum efficiency and versatility to the project.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("TET@sdc.com",1, "The Electrical Tester", "http://i.imgur.com/3TLT7QN.png", "The Electrical Tester offers passive detection to alert the user immediately if they are working in the vicinity of a live circuit that could potentially cause electrical shock.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("THB@sdc.com",1, "The Hi Ball", "http://i.imgur.com/3TLT7QN.png", "The Electrical Tester offers passive detection to alert the user immediately if they are working in the vicinity of a live circuit that could potentially cause electrical shock.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("BMSAG@sdc.com",1, "Bombyx Mori Silk AntiMicrobial Gel", "http://i.imgur.com/3TLT7QN.png", "The team proposes a gel made of Bombyx Mori silk, or silkworm cocoon silk, mixed with an antimicrobial agent, like silver nanoparticles.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("CQ@sdc.com",1, "Coanda Quadcopter", "http://i.imgur.com/3TLT7QN.png", "Our team’s solution to the flight duration problem involves adding an additional means of generating lift without significantly increasing the cost or weight of the UAV. ");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("DSTDT@sdc.com",1, "Damping System Test Drop Tower", "http://i.imgur.com/3TLT7QN.png", "Our solution involves a tower that is able to generate a wide range of shocks into a damping system with a large amount of control while allowing the system to be interchanged with others.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("HSG@sdc.com",1, "Harco Spray Gun", "http://i.imgur.com/3TLT7QN.png", "The redesigned gun improves ergonomics while reducing weight by 1-1.5 lbs due to the use of plastic instead of aluminum.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("Jox-t@sdc.com",1, "Jox-T", "http://i.imgur.com/3TLT7QN.png", "The idea of this tee is to have the hitter work on getting their bat head through the zone to make full contact with the ball while involving no recollection of the hit ball. ");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("AH2@sdc.com",1, "Automated Heliodon V2.0", "http://i.imgur.com/3TLT7QN.png", "Our goal is to modernize this technology with simple control systems and a user-friendly interface.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("UEC@sdc.com",1, "Universally Expanding Cage", "http://i.imgur.com/3TLT7QN.png", "The Universally Expanding Cage (UEC) can expand in height just like the existing devices, but the UEC can simultaneously expand both laterally and posteriorly. ");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("WE@sdc.com",1, "Wastewater Evaporator", "http://i.imgur.com/3TLT7QN.png", "The Surface Evaporator is an economical approach to providing a low-cost evaporation solution to EPA regulated counties across the United States. ");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("APEL@sdc.com",1, "Accurate Photo-Emitting Liquid (APEL) Scan", "http://i.imgur.com/3TLT7QN.png", "We also take advantage of CMOS technology with a SiPM fabricated on a chip that requires much less power than traditional ones. ");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("CTRM@sdc.com",1, "Carpal Tunnel Relief Massager", "http://i.imgur.com/3TLT7QN.png", "Our team’s solution is to build a device that mimics the actions of a physical therapist so clients can have consecutive sessions without a doctor visit.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("HHV3@sdc.com",1, "Hailey's Hang V3.0", "http://i.imgur.com/3TLT7QN.png", "Hailey’s Hand 3.0 addresses the identified problems, and either improves upon, or expands the scope of, previous Hailey’s Hand Designs. ");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("SPHERD@sdc.com",1, "Silicon Photomultiplier High Energy Radiation Detector", "http://i.imgur.com/3TLT7QN.png", "Our solution will utilize an in-house designed SiPM that will greatly reduce the cost of a scintillation counter device.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("ZMED@sdc.com",1, "Z-Med Alert", "http://i.imgur.com/3TLT7QN.png", "Z-med Alert attempts to balance all the features of the current market products by using newer technology at a significantly reduced cost.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("PA@sdc.com",1, "Project Apollo", "http://i.imgur.com/3TLT7QN.png", "Bacon ipsum dolor amet capicola jowl tail chicken swine burgdoggen ribeye fatback beef ribs tenderloin andouille cow.");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("MGIILS@sdc.com",1, "Micro Grid II: Load Share", "http://i.imgur.com/3TLT7QN.png", "Ham irure ham hock spare ribs, ground round et fugiat pork belly. Ut meatball ut salami aute.");


INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 1", "2017-05-04 08:00:00", "2017-05-04 08:15:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 2", "2017-05-04 08:15:00", "2017-05-04 08:30:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 3", "2017-05-04 08:30:00", "2017-05-04 08:45:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 4", "2017-05-04 08:45:00", "2017-05-04 09:00:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 5", "2017-05-04 09:00:00", "2017-05-04 09:15:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 6", "2017-05-04 09:15:00", "2017-05-04 09:30:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 7", "2017-05-04 09:30:00", "2017-05-04 09:45:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 8", "2017-05-04 10:00:00", "2017-05-04 10:15:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 9", "2017-05-04 10:15:00", "2017-05-04 10:30:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 10", "2017-05-04 10:30:00", "2017-05-04 10:45:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 11", "2017-05-04 10:45:00", "2017-05-04 11:00:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 12", "2017-05-04 11:00:00", "2017-05-04 11:15:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 13", "2017-05-04 11:15:00", "2017-05-04 11:30:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 14", "2017-05-04 11:30:00", "2017-05-04 11:45:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 15", "2017-05-04 11:45:00", "2017-05-04 12:00:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 16", "2017-05-04 12:00:00", "2017-05-04 12:15:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 17", "2017-05-04 12:15:00", "2017-05-04 12:30:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 18", "2017-05-04 14:05:00", "2017-05-04 14:20:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 19", "2017-05-04 14:20:00", "2017-05-04 14:35:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 20", "2017-05-04 14:35:00", "2017-05-04 14:50:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 21", "2017-05-04 14:50:00", "2017-05-04 15:05:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 22", "2017-05-04 15:05:00", "2017-05-04 15:20:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 23", "2017-05-04 15:20:00", "2017-05-04 15:35:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 24", "2017-05-04 15:35:00", "2017-05-04 15:50:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 25", "2017-05-04 16:05:00", "2017-05-04 16:20:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 26", "2017-05-04 16:20:00", "2017-05-04 16:35:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 27", "2017-05-04 16:35:00", "2017-05-04 16:50:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 28", "2017-05-04 16:50:00", "2017-05-04 17:05:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 29", "2017-05-04 17:05:00", "2017-05-04 17:20:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 30", "2017-05-04 17:20:00", "2017-05-04 17:35:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Presentation 31", "2017-05-04 17:35:00", "2017-05-04 17:50:00", "#ffffff", "#FAE3E3");



INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("1", "Steven Brooks", 0, "2017-03-28 00:00:00", "0.0.0.0", "brooks@unlv.nevada.edu", 1, 2);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("2", "Lily Lei", 0, "2017-03-28 00:00:00", "0.0.0.0", "leil1@unlv.nevada.edu", 0, 3);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("3", "Arjee M", 0, "2017-11-03 00:00:00", "0.0.0.0", "mendej2@unlv.nevada.edu", 1, 2);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("4", "HP", 0, "2017-03-28 00:00:00", "0.0.0.0", "hpexample@email.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("5", "Apple", 0, "2017-03-28 00:00:00", "0.0.0.0", "appleexample@email.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("6", "Tesla", 0, "2017-03-28 00:00:00", "0.0.0.0", "teslaexample@email.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("7", "AT&T", 0, "2017-03-28 00:00:00", "0.0.0.0", "attexample@email.com", 0, 1);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("google-oauth2|105950922553210130192", "Grant Organizer", 0, "2017-03-28 00:00:00", "0.0.0.0", "gmercer015@gmail.com", 0, 3);
INSERT INTO users(user_id, name, login_count, last_login, last_ip, email, gender, permissions) VALUES("8", "Grant Exhibitor", 0, "2017-03-28 00:00:00", "0.0.0.0", "mercerg2@unlv.nevada.edu", 0, 1);

INSERT INTO permitted_organizers(organizer_email, conference_id) VALUES("gmercer015@gmail.com",1 );
INSERT INTO permitted_organizers(organizer_email, conference_id) VALUES("leil1@unlv.nevada.edu",1 );
INSERT INTO permitted_organizers(organizer_email, conference_id) VALUES("conventionlogisticstracker@gmail.com",1 );
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("hpexample@email.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("appleexample@email.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("teslaexample@email.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("attexample@email.com",1);
INSERT INTO permitted_exhibitors(exhibitor_email, conference_id) VALUES("mercerg2@unlv.nevada.edu",1);

INSERT INTO organizers(organizer_email, conference) VALUES("gmercer015@gmail.com", 1);
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("hpexample@email.com", 1, "HP", "http://i.imgur.com/qtDcA1z.png?1", "HP bio sample");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("appleexample@email.com", 1, "Apple", "http://i.imgur.com/3Vhuu59.jpg?1", "Apple bio sample");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("teslaexample@email.com", 1, "Tesla", "http://i.imgur.com/TV171o1.png?1", "Telsa bio Sample");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("attexample@email.com", 1, "AT&T", "http://i.imgur.com/s7YTXDu.png?1", "ATT bio sample");
INSERT INTO exhibitors(exhibitor_email, conference, company_name, logo_url, bio) VALUES("mercerg2@unlv.nevada.edu", 1, "Grant Exhibitor", "http://i.imgur.com/3TLT7QN.png", "Grant bio sample");

INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "AT&T Giveaway", "2017-04-28 08:00:00", "2017-04-29 00:00:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Tesla Keynote Speech", "2017-04-28 09:00:00", "2017-04-28 11:00:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Apple Design Experience", "2017-04-28 00:00:00", "2017-05-03 04:00:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "HP Future Product Plan", "2017-04-28 00:00:00", "2017-04-29 00:00:00", "#ffffff", "#FAE3E3");
INSERT INTO schedule(conference, event_name, start_time, end_time,primary_color,secondary_color) VALUES(1, "Conference Raffle Drawing", "2017-05-01 09:00:00", "2017-05-01 10:00:00", "#ffffff", "#FAE3E3");

INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "Senior Design Kicks Off! 8 am 5/4/17", "http://i.imgur.com/3TLT7QN.png", "Check out all the projects of this year's teams!", "UNLV");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "Swag Giveaway", "http://i.imgur.com/s7YTXDu.png?1", "Stop by the AT&T booth for free swag!", "AT&T");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "Guest Speaker", "http://i.imgur.com/TV171o1.png?1", "Come listen to our head of AI devlopment speak on his work process.", "Tesla");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "New Product Unveiling", "http://i.imgur.com/qtDcA1z.png?1", "See the new product we have been working on for the last year!", "HP");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "UX Team Panel", "http://i.imgur.com/3Vhuu59.jpg?1", "Ask a few members of our User Experience team any questions you may have!", "Apple");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "CLT Special Event", "http://i.imgur.com/65LAMrK.png", "Convention Logistics Tracker Dance Battle!", "CLT");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "S.B. LV Poetry Slam", "http://i.imgur.com/65LAMrK.png", "Slam Poetry from renowned author S.Brooks LV.", "AT&T");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "Free Lunch at Great Hall", "http://i.imgur.com/3TLT7QN.png", "Sandwiches and drinks, courtesy of UNLV", "UNLV");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "Private funding opportunity", "http://i.imgur.com/qtDcA1z.png?1", "HP will listen to product pitches for 1 hour.", "HP");
INSERT INTO news(conference, title, logo_url, text, author) VALUES (1, "Omega Event", "http://i.imgur.com/3TLT7QN.png", "I am the alpha and the omega. All begins and ends with me.", "UNLV");